// uploadAllData.js
import { db } from "./firebaseConfig.js"; // Adjust the path if needed
import { collection, doc, setDoc } from "firebase/firestore";
import { Client } from "@googlemaps/google-maps-services-js";

// Initialize Google Maps client
const gmaps = new Client({});
const GOOGLE_MAPS_API_KEY = "AIzaSyAy2J-28fvMFNZ7JOUYVAAENpXWcv-lHLQ"; // Your API key

// Fare metrics data
const fareMetrics = [
  { distance: 1, regular: 12, discounted: 9.5 },
  { distance: 2, regular: 12, discounted: 9.5 },
  { distance: 3, regular: 12, discounted: 9.5 },
  { distance: 4, regular: 12, discounted: 9.5 },
  { distance: 5, regular: 13.75, discounted: 11 },
  { distance: 6, regular: 15.5, discounted: 12.5 },
  { distance: 7, regular: 17.5, discounted: 14 },
  { distance: 8, regular: 19.25, discounted: 15.25 },
  { distance: 9, regular: 21, discounted: 16.75 },
  { distance: 10, regular: 22.75, discounted: 18.25 },
  { distance: 11, regular: 24.5, discounted: 19.75 },
  { distance: 12, regular: 26.5, discounted: 21 },
  { distance: 13, regular: 28.25, discounted: 22.5 },
  { distance: 14, regular: 30, discounted: 24 },
  { distance: 15, regular: 31.75, discounted: 25.5 },
  { distance: 16, regular: 33.5, discounted: 27 },
  { distance: 17, regular: 35.5, discounted: 28.25 },
  { distance: 18, regular: 37.25, discounted: 29.75 },
  { distance: 19, regular: 39, discounted: 31.25 },
  { distance: 20, regular: 40.75, discounted: 32.75 },
  { distance: 21, regular: 42.5, discounted: 34 },
  { distance: 22, regular: 44.5, discounted: 35 },
  { distance: 23, regular: 46.25, discounted: 37 },
  { distance: 24, regular: 48, discounted: 38.5 },
  { distance: 25, regular: 49.75, discounted: 39.75 },
  { distance: 26, regular: 51.5, discounted: 41.25 },
  { distance: 27, regular: 53.5, discounted: 42.75 },
  { distance: 28, regular: 55.25, discounted: 44.25 },
  { distance: 29, regular: 57, discounted: 45.5 },
  { distance: 30, regular: 58.75, discounted: 47 },
  { distance: 31, regular: 60.5, discounted: 48.5 },
  { distance: 32, regular: 62.5, discounted: 50 },
  { distance: 33, regular: 64.25, discounted: 51.25 },
  { distance: 34, regular: 66, discounted: 52.75 },
  { distance: 35, regular: 67.75, discounted: 54.25 },
  { distance: 36, regular: 69.5, discounted: 55.75 },
  { distance: 37, regular: 71.5, discounted: 57 },
  { distance: 38, regular: 73.25, discounted: 58.5 },
  { distance: 39, regular: 75, discounted: 60 },
  { distance: 40, regular: 76.75, discounted: 61.5 },
  { distance: 41, regular: 78.5, discounted: 63 },
  { distance: 42, regular: 80.5, discounted: 64.25 },
  { distance: 43, regular: 82.25, discounted: 65.75 },
  { distance: 44, regular: 84, discounted: 67.25 },
  { distance: 45, regular: 85.75, discounted: 68.75 },
  { distance: 46, regular: 87.5, discounted: 70 },
  { distance: 47, regular: 89.5, discounted: 71.5 },
  { distance: 48, regular: 91.25, discounted: 73 },
  { distance: 49, regular: 93, discounted: 74.5 },
  { distance: 50, regular: 94.75, discounted: 75.75 },
];

// Routes data
const routes = [
  {
    name: "Diretso Daraga to Legazpi",
    start: "Daraga",
    end: "Legazpi",
    via: ["Tahao Road"],
    distance: 6,
    landmarks: [
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Jollibee Albay",
      "Robinsons Supermarket Albay",
      "Divine Word College of Legazpi",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Bangko Sentral ng Pilipinas",
      "STI College - Legazpi",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "Ayala Malls Legazpi",
      "LCC Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
    ],
    zones: [
      "Sipi",
      "Sagpon",
      "Em's Barrio",
      "Old Albay District",
      "Ilawod",
      "Cabagnan",
      "Bitano",
      "Legazpi Port District",
    ],
    startCoords: { lat: 13.148, lon: 123.712 },
    endCoords: { lat: 13.139, lon: 123.743 },
    isPrimary: true,
  },
  {
    name: "Diretso Legazpi to Daraga",
    start: "Legazpi",
    end: "Daraga",
    via: ["Tahao Road"],
    distance: 6,
    landmarks: [
      "Ayala Malls Legazpi",
      "Albay Doctors Hospital",
      "St. Raphael the Archangel Parish",
      "LCC Legazpi",
      "J&T Express - Legazpi",
      "Tanchuling College",
      "STI College - Legazpi",
      "Iglesia ni Cristo",
      "Bangko Sentral ng Pilipinas",
      "St. Agnes' Academy",
      "Unitop Legazpi",
      "Divine Word College of Legazpi",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Bicol College",
      "Bicol University Daraga Campus",
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
    ],
    zones: [
      "Legazpi Port District",
      "Cabagnan",
      "Ilawod",
      "Old Albay District",
      "Em's Barrio",
      "Sagpon",
      "Sipi",
    ],
    startCoords: { lat: 13.139, lon: 123.743 },
    endCoords: { lat: 13.148, lon: 123.712 },
    isPrimary: true,
  },
  {
    name: "Alternate Daraga to Legazpi",
    start: "Daraga",
    end: "Arimbay",
    via: ["Alternate Road"],
    distance: 11,
    landmarks: [
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Albay Astrodome",
      "University of Santo Tomas - Legazpi Hospital",
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "Yashano Mall Legazpi",
      "Pacific Mall",
      "Gaisano Mall",
      "Hotel Lucca",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "Ayala Malls Legazpi",
      "LCC Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
    ],
    zones: [
      "Sipi",
      "Sagpon",
      "Em's Barrio",
      "Old Albay District",
      "Ilawod",
      "Bitano",
      "Legazpi Port District",
      "Bonot",
      "Rawis",
      "Arimbay",
    ],
    startCoords: { lat: 13.148, lon: 123.712 },
    endCoords: { lat: 13.18, lon: 123.752 },
    isPrimary: true,
  },
  {
    name: "Alternate Legazpi to Daraga",
    start: "Arimbay",
    end: "Daraga",
    via: ["Alternate Road"],
    distance: 10,
    landmarks: [
      "Arimbay Parish Church",
      "Abenson Rawis Legazpi Albay",
      "Civil Service Commission",
      "Brgy. 42 Rawis Barangay Hall",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Land Transportation Office",
      "Land Transportation Franchising & Regulatory Board",
      "Department of Environment and Natural Resources",
      "University of Santo Tomas - Legazpi",
      "Legazpi Public Cemetery",
      "Albay Doctors Hospital",
      "St. Raphael the Archangel Parish",
      "LCC Legazpi",
      "Ayala Malls Legazpi",
      "Gaisano Mall",
      "Pacific Mall",
      "Yashano Mall Legazpi",
      "Legazpi Grand Terminal",
      "SM City Legazpi",
      "University of Santo Tomas - Legazpi Hospital",
      "Albay Astrodome",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Bicol College",
      "Bicol University Daraga Campus",
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
    ],
    zones: [
      "Arimbay",
      "Rawis",
      "Legazpi Port District",
      "Bitano",
      "Ilawod",
      "Old Albay District",
      "Em's Barrio",
      "Sagpon",
      "Bonot",
      "Sipi",
    ],
    startCoords: { lat: 13.18, lon: 123.752 },
    endCoords: { lat: 13.148, lon: 123.712 },
    isPrimary: true,
  },
  {
    name: "Rawis to Daraga A",
    start: "Arimbay",
    end: "Daraga",
    via: ["Lakandule Drive"],
    distance: 12,
    landmarks: [
      "Arimbay Parish Church",
      "Abenson Rawis Legazpi Albay",
      "Civil Service Commission",
      "Brgy. 42 Rawis Barangay Hall",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Land Transportation Office",
      "Land Transportation Franchising & Regulatory Board",
      "Department of Environment and Natural Resources",
      "University of Santo Tomas - Legazpi",
      "Legazpi Public Cemetery",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Ayala Malls Legazpi",
      "Pacific Mall",
      "Gaisano Mall",
      "Legazpi Garden Hotel",
      "Legazpi City Water District",
      "Our Lady's Village",
      "Kalayaan Park",
      "Gogon Central School",
      "The Marison Hotel",
      "Cruzada Barangay Hall",
      "Sunrise Subdivision",
      "Sampaguita Tourist Inn",
      "University of Santo Tomas - Legazpi Hospital",
      "Albay Astrodome",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Bicol College",
      "Bicol University Daraga Campus",
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
    ],
    zones: [
      "Arimbay",
      "Rawis",
      "Bonot",
      "Legazpi Port District",
      "Bitano",
      "Gogon",
      "Bogtong",
      "Cruzada",
      "Washington",
      "Old District Albay",
      "Sipi",
      "Sagpon",
      "Em's Barrio",
    ],
    startCoords: { lat: 13.18, lon: 123.752 },
    endCoords: { lat: 13.148, lon: 123.712 },
    isPrimary: true,
  },
  {
    name: "Daraga to Rawis A",
    start: "Daraga",
    end: "Arimbay",
    via: ["Tahao Road"],
    distance: 10,
    landmarks: [
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Legazpi City Hall",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Jollibee Albay",
      "Robinsons Supermarket Albay",
      "Divine Word College of Legazpi",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Bangko Sentral ng Pilipinas",
      "Iglesia ni Cristo",
      "STI College - Legazpi",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "Ayala Malls Legazpi",
      "Albay Doctors Hospital",
      "St. Raphael the Archangel Parish",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
    ],
    zones: [
      "Em's Barrio",
      "Sagpon",
      "Old District Albay",
      "Ilawod",
      "Cabagnan",
      "Legazpi Port District",
      "Bonot",
      "Rawis",
      "Sipi",
      "Arimbay",
    ],
    startCoords: { lat: 13.148, lon: 123.712 },
    endCoords: { lat: 13.18, lon: 123.752 },
    isPrimary: true,
  },
  {
    name: "Rawis to Daraga B",
    start: "Arimbay",
    end: "Daraga",
    via: ["Alternate Road"],
    distance: 10,
    landmarks: [
      "Arimbay Parish Church",
      "Abenson Rawis Legazpi Albay",
      "Civil Service Commission",
      "Brgy. 42 Rawis Barangay Hall",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Land Transportation Office",
      "Land Transportation Franchising & Regulatory Board",
      "Department of Environment and Natural Resources",
      "University of Santo Tomas - Legazpi",
      "Legazpi Public Cemetery",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Ayala Malls Legazpi",
      "Pacific Mall",
      "Gaisano Mall",
      "Yashano Mall Legazpi",
      "University of Santo Tomas - Legazpi Hospital",
      "Albay Astrodome",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Bicol College",
      "Bicol University Daraga Campus",
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
    ],
    zones: [
      "Arimbay",
      "Rawis",
      "Legazpi Port District",
      "Bitano",
      "Ilawod",
      "Old Albay District",
      "Em's Barrio",
      "Sagpon",
      "Sipi",
    ],
    startCoords: { lat: 13.18, lon: 123.752 },
    endCoords: { lat: 13.148, lon: 123.712 },
    isPrimary: true,
  },
  {
    name: "Daraga to Rawis B",
    start: "Daraga",
    end: "Arimbay",
    via: ["Lakandule Drive"],
    distance: 12,
    landmarks: [
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Albay Astrodome",
      "University of Santo Tomas - Legazpi Hospital",
      "Sampaguita Tourist Inn",
      "Sunrise Subdivision",
      "Legazpi Garden Hotel",
      "The Marison Hotel",
      "Gogon Central School",
      "Kalayaan Park",
      "Our Lady's Village",
      "Legazpi City Water District",
      "Cruzada Barangay Hall",
      "Gaisano Mall",
      "Pacific Mall",
      "Hotel Lucca",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "Ayala Malls Legazpi",
      "Albay Doctors Hospital",
      "St. Raphael the Archangel Parish",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
    ],
    zones: [
      "Arimbay",
      "Rawis",
      "Legazpi Port District",
      "Bitano",
      "Ilawod",
      "Old Albay District",
      "Em's Barrio",
      "Sagpon",
      "Sipi",
    ],
    startCoords: { lat: 13.18, lon: 123.752 },
    endCoords: { lat: 13.148, lon: 123.712 },
    isPrimary: true,
  },
  {
    name: "Loop 1 Legazpi to Daraga",
    start: "Bonot",
    end: "Daraga",
    via: ["Brgy. Bogtong"],
    distance: 6,
    landmarks: [
      "Legazpi Public Cemetery",
      "Pristine Memorial Gardents",
      "ACE Medical Center Legazpi",
      "Albay Park & Wildlife",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
    ],
    zones: ["Bonot", "Gogon", "Bogtong", "Tagas", "Maroroy", "Bañag", "Sipi"],
    startCoords: { lat: 13.16, lon: 123.749 },
    endCoords: { lat: 13.154, lon: 123.711 },
    isPrimary: true,
  },
  {
    name: "Loop 1 Daraga to Legazpi",
    start: "Daraga",
    end: "Bonot",
    via: ["Rizal St."],
    distance: 8,
    landmarks: [
      "Daraga Church",
      "Daraga Municipal Hall",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Jollibee Albay",
      "Robinsons Supermarket Albay",
      "Divine Word College of Legazpi",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Bangko Sentral ng Pilipinas",
      "Iglesia ni Cristo",
      "STI College - Legazpi",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "Ayala Malls Legazpi",
      "LCC Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Legazpi Public Cemetery",
    ],
    zones: [
      "Bañag",
      "Sipi",
      "Sagpon",
      "Em's Barrio",
      "Ilawod",
      "Old Albay District",
      "Cabagnan",
      "Bitano",
      "Legazpi Port District",
    ],
    startCoords: { lat: 13.154, lon: 123.711 },
    endCoords: { lat: 13.16, lon: 123.749 },
    isPrimary: true,
  },
  {
    name: "Loop 2 Legazpi to Daraga",
    start: "Bonot",
    end: "Daraga",
    via: ["Peñaranda St."],
    distance: 6,
    landmarks: [
      "Legazpi Public Cemetery",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Ayala Malls Legazpi",
      "St. Raphael the Archangel Parish",
      "LCC Legazpi",
      "J&T Express - Legazpi",
      "Tanchuling College",
      "STI College - Legazpi",
      "Iglesia ni Cristo",
      "Bangko Sentral ng Pilipinas",
      "St. Agnes' Academy",
      "Unitop Legazpi",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Divine Word College of Legazpi",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Bicol College",
      "Bicol University Daraga Campus",
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
    ],
    zones: [
      "Legazpi Port District",
      "Bitano",
      "Cabagnan",
      "Old Albay District",
      "Ilawod",
      "Em's Barrio",
      "Sagpon",
      "Sipi",
      "Bañag",
    ],
    startCoords: { lat: 13.16, lon: 123.749 },
    endCoords: { lat: 13.139, lon: 123.743 },
    isPrimary: true,
  },
  {
    name: "Loop 2 Daraga to Legazpi",
    start: "Daraga",
    end: "Bonot",
    via: ["Binitayan Road"],
    distance: 8,
    landmarks: [
      "LCC Daraga",
      "BIGGS Daraga",
      "Shell Daraga",
      "Daraga Municipal Hall",
      "Daraga Church",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Albay Park & Wildlife",
      "ACE Medical Center Legazpi",
      "Pristine Memorial Gardents",
      "Legazpi Public Cemetery",
    ],
    zones: ["Sipi", "Bañag", "Maroroy", "Tagas", "Bogtong", "Gogon", "Bonot"],
    startCoords: { lat: 13.139, lon: 123.743 },
    endCoords: { lat: 13.16, lon: 123.749 },
    isPrimary: true,
  },
  {
    name: "Camalig to Legazpi",
    start: "Camalig",
    end: "Legazpi",
    via: ["Tahao Road"],
    distance: 14,
    landmarks: [
      "Camalig Market",
      "Camalig Municipal Hall",
      "Sumlang Lake",
      "Daraga Community College",
      "DComC",
      "Carmela's Resort",
      "Cagsawa Ruins",
      "Mayon SkyDrive ATV Adventure",
      "Daraga Doctor's Hospital",
      "Daraga Church",
      "Daraga Municipal Hall",
      "Daraga Public Market",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Jollibee Albay",
      "Robinsons Supermarket Albay",
      "Divine Word College of Legazpi",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Bangko Sentral ng Pilipinas",
      "Iglesia ni Cristo",
      "STI College - Legazpi",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "LCC Legazpi",
      "NBI - Bicol Regional Office",
      "St. Padre Pio Chapel",
      "Embarcadero de Lagazpi",
      "Kapuntukan Hill",
      "JB Legazpi Medical Clinic",
      "Hotel St. Ellis",
      "University of Santo Tomas - Legazpi Peñaranda Campus",
      "Albay Doctors Hospital",
      "Ayala Malls Legazpi",
    ],
    zones: [
      "Sumlang",
      "Salvacion",
      "Malabog",
      "Busay",
      "Cullat",
      "Bañag",
      "Sipi",
      "Sagpon",
      "Em's Barrio",
      "Ilawod",
      "Old Albay District",
      "Cabagnan",
      "Bitano",
      "Legazpi Port District",
    ],
    startCoords: { lat: 13.157, lon: 123.654 },
    endCoords: { lat: 13.147, lon: 123.751 },
    isPrimary: true,
  },
  {
    name: "Legazpi to Camalig",
    start: "Legazpi",
    end: "Camalig",
    via: ["Tahao Road"],
    distance: 14,
    landmarks: [
      "Ayala Malls Legazpi",
      "Legazpi Public Market",
      "Hotel Sentro Legazpi",
      "STI College - Legazpi",
      "Iglesia ni Cristo",
      "Bangko Sentral ng Pilipinas",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Divine Word College of Legazpi",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Department of Health Regional Compound",
      "Doña Maria Subdivision Park",
      "Daraga Tourist Inn",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Mayon SkyDrive ATV Adventure",
      "Cagsawa Ruins",
      "Carmela's Resort",
      "DComC",
      "Daraga Community College",
      "Sumlang Lake",
      "Camalig Municipal Hall",
      "Camalig Market",
    ],
    zones: [
      "Legazpi Port District",
      "Bitano",
      "Cabagnan",
      "Old Albay District",
      "Ilawod",
      "Em's Barrio",
      "Sagpon",
      "Maroroy",
      "Bañag",
      "Cullat",
      "Busay",
      "Malabog",
      "Salvacion",
      "Sumlang",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.157, lon: 123.654 },
    isPrimary: true,
  },
  {
    name: "Guinobatan to Legazpi",
    start: "Guinobatan",
    end: "Legazpi",
    via: [],
    distance: 21,
    landmarks: [
      "Guinobatan Plaza",
      "Guinobatan Public Market",
      "Guinobatan Town Hall",
      "Guinobatan Church",
      "Camalig Market",
      "Camalig Municipal Hall",
      "Sumlang Lake",
      "Daraga Community College",
      "DComC",
      "Carmela's Resort",
      "Cagsawa Ruins",
      "Mayon SkyDrive ATV Adventure",
      "Daraga Doctor's Hospital",
      "Daraga Church",
      "Daraga Municipal Hall",
      "Daraga Public Market",
      "Shell Daraga",
      "BIGGS Daraga",
      "LCC Daraga",
      "Bicol University Daraga Campus",
      "Bicol College",
      "Bicol Regional Hospital and Medical Center",
      "Bicol University",
      "Camp Ola Legazpi City",
      "Albay Provincial Capitol",
      "Peñaranda Park",
      "St. Gregory the Great Cathedral",
      "Legazpi City Hall",
      "Jollibee Albay",
      "Robinsons Supermarket Albay",
      "Divine Word College of Legazpi",
      "Unitop Legazpi",
      "St. Agnes' Academy",
      "Bangko Sentral ng Pilipinas",
      "Iglesia ni Cristo",
      "STI College - Legazpi",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "LCC Legazpi",
      "NBI - Biocl Regional Office",
      "St. Padre Pio Chapel",
      "Embarcadero de Lagazpi",
      "Kapuntukan Hill",
      "JB Legazpi Medical Clinic",
      "Hotel St. Ellis",
      "University of Santo Tomas - Legazpi Peñaranda Campus",
      "Albay Doctors Hospital",
      "Ayala Malls Legazpi",
    ],
    zones: [
      "Travesia",
      "Libod",
      "Ilawod, Camalig",
      "Sumlang",
      "Salvacion",
      "Malabog",
      "Busay",
      "Cullat",
      "Bañag",
      "Sipi",
      "Sagpon",
      "Em's Barrio",
      "Ilawod",
      "Old Albay District",
      "Cabagnan",
      "Bitano",
      "Legazpi Port District",
    ],
    startCoords: { lat: 13.191, lon: 123.6 },
    endCoords: { lat: 13.147, lon: 123.751 },
    isPrimary: true,
  },
  {
    name: "Legazpi to Guinobatan",
    start: "Legazpi",
    end: "Guinobatan",
    via: [],
    distance: 21,
    landmarks: [
      "Ayala Malls Legazpi",
      "Pacific Mall",
      "Gaisano Mall",
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "St. Agnes' Academy",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Divine Word College of Legazpi",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Department of Health Regional Compound",
      "Doña Maria Subdivision Park",
      "Daraga Tourist Inn",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Mayon SkyDrive ATV Adventure",
      "Cagsawa Ruins",
      "Carmela's Resort",
      "DComC",
      "Daraga Community College",
      "Sumlang Lake",
      "Camalig Municipal Hall",
      "Camalig Market",
      "Guinobatan Plaza",
      "Guinobatan Church",
      "Guinobatan Town Hall",
      "Guinobatan Public Market",
    ],
    zones: [
      "Legazpi Port District",
      "Bitano",
      "Cabagnan",
      "Old Albay District",
      "Ilawod",
      "Em's Barrio",
      "Sagpon",
      "Maroroy",
      "Bañag",
      "Cullat",
      "Busay",
      "Malabog",
      "Salvacion",
      "Sumlang",
      "Ilawod, Camalig",
      "Libod",
      "Travesia",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.191, lon: 123.6 },
    isPrimary: true,
  },
  {
    name: "Legazpi to Ligao",
    start: "Legazpi",
    end: "Ligao",
    via: [],
    distance: 31,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "St. Agnes' Academy",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Divine Word College of Legazpi",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Department of Health Regional Compound",
      "Doña Maria Subdivision Park",
      "Daraga Tourist Inn",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Mayon SkyDrive ATV Adventure",
      "Cagsawa Ruins",
      "Carmela's Resort",
      "DComC",
      "Daraga Community College",
      "Sumlang Lake",
      "Camalig Municipal Hall",
      "Camalig Market",
      "Guinobatan Plaza",
      "Guinobatan Church",
      "Guinobatan Town Hall",
      "Guinobatan Public Market",
      "Mount Masaraga Viewpoint",
      "Ligao People's Park",
      "Kawa-Kawa Hill and Natural Park",
      "St. Stephen Protomartyr Parish Church",
      "Ligao Public Market",
      "Ligao City Hall",
    ],
    zones: [
      "Bitano",
      "Old Albay District",
      "Ilawod",
      "Em's Barrio",
      "Sagpon",
      "Maroroy",
      "Bañag",
      "Cullat",
      "Busay",
      "Malabog",
      "Salvacion",
      "Sumlang",
      "Ilawod, Camalig",
      "Libod",
      "Travesia",
      "Morera",
      "Binogsacan Lower",
      "Banao",
      "Paulog",
      "Tuburan",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.24, lon: 123.535 },
    isPrimary: false,
  },
  {
    name: "Legazpi to Oas",
    start: "Legazpi",
    end: "Oas",
    via: [],
    distance: 35,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "St. Agnes' Academy",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Divine Word College of Legazpi",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "Camp Ola Legazpi City",
      "Bicol University",
      "Bicol Regional Hospital and Medical Center",
      "Department of Health Regional Compound",
      "Doña Maria Subdivision Park",
      "Daraga Tourist Inn",
      "Daraga Catholic Cemetery",
      "Daraga Doctor's Hospital",
      "Mayon SkyDrive ATV Adventure",
      "Cagsawa Ruins",
      "Carmela's Resort",
      "DComC",
      "Daraga Community College",
      "Sumlang Lake",
      "Camalig Municipal Hall",
      "Camalig Market",
      "Guinobatan Plaza",
      "Guinobatan Church",
      "Guinobatan Town Hall",
      "Guinobatan Public Market",
      "Mount Masaraga Viewpoint",
      "Ligao People's Park",
      "Kawa-Kawa Hill and Natural Park",
      "St. Stephen Protomartyr Parish Church",
      "Ligao Public Market",
      "Ligao City Hall",
      "Oas Community College",
      "St. Michael the Archangel Parish Church",
      "Oas Public Market",
      "Oas Municipal Hall",
    ],
    zones: [
      "Bitano",
      "Old Albay District",
      "Ilawod",
      "Em's Barrio",
      "Sagpon",
      "Maroroy",
      "Bañag",
      "Cullat",
      "Busay",
      "Malabog",
      "Salvacion",
      "Sumlang",
      "Ilawod, Camalig",
      "Libod",
      "Travesia",
      "Morera",
      "Binogsacan Lower",
      "Banao",
      "Paulog",
      "Tuburan",
      "Santa Cruz",
      "Binatagan",
      "Bagumbayan",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.24, lon: 123.535 },
    isPrimary: false,
  },
  {
    name: "Legazpi to Sto. Domingo",
    start: "Legazpi",
    end: "Sto. Domingo",
    via: [],
    distance: 12,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "Pacific Mall",
      "Gaisano Mall",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "LCC Legazpi",
      "Ayala Malls Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
      "Black Sand Beaches",
      "Sto. Domingo People's Center",
      "Sto. Domingo Public Market",
      "Sto. Domingo Municipal Hall",
    ],
    zones: [
      "Bitano",
      "Legazpi Port District",
      "Bonot",
      "Rawis",
      "Arimbay",
      "Bigaa",
      "Lidong",
      "San Isidro",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.235, lon: 123.776 },
    isPrimary: false,
  },
  {
    name: "Legazpi to Malilipot",
    start: "Legazpi",
    end: "Malilipot",
    via: [],
    distance: 22,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "Pacific Mall",
      "Gaisano Mall",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "LCC Legazpi",
      "Ayala Malls Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
      "Black Sand Beaches",
      "Sto. Domingo People's Center",
      "Sto. Domingo Public Market",
      "Sto. Domingo Municipal Hall",
      "Vanishing Island",
      "Busay Falls",
      "Malilipot Public Market",
      "Malilipot Municipal Hall",
    ],
    zones: [
      "Bitano",
      "Legazpi Port District",
      "Bonot",
      "Rawis",
      "Arimbay",
      "Bigaa",
      "Lidong",
      "San Isidro",
      "FIdel Surtida",
      "Santa Misericordia",
      "San Fernando",
      "Bonga Upper",
      "San Jose",
      "San Francisco",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.399, lon: 123.736 },
    isPrimary: false,
  },
  {
    name: "Legazpi to Tabaco",
    start: "Legazpi",
    end: "Tabaco",
    via: [],
    distance: 38,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "Pacific Mall",
      "Gaisano Mall",
      "Tanchuling College",
      "J&T Express - Legazpi",
      "LCC Legazpi",
      "Ayala Malls Legazpi",
      "St. Raphael the Archangel Parish",
      "Albay Doctors Hospital",
      "Legazpi Public Cemetery",
      "University of Santo Tomas - Legazpi",
      "Department of Environment and Natural Resources",
      "Land Transportation Franchising & Regulatory Board",
      "Land Transportation Office",
      "Mariners' Polytechnic Colleges Foundation Legazpi City",
      "Brgy. 42 Rawis Barangay Hall",
      "Civil Service Commission",
      "Abenson Rawis Legazpi Albay",
      "Arimbay Parish Church",
      "Black Sand Beaches",
      "Sto. Domingo People's Center",
      "Sto. Domingo Public Market",
      "Sto. Domingo Municipal Hall",
      "Vanishing Island",
      "Busay Falls",
      "Malilipot Public Market",
      "Malilipot Municipal Hall",
      "Tabaco Port",
      "Tabaco Public Market",
      "Tabaco City Hall",
    ],
    zones: [
      "Bitano",
      "Legazpi Port District",
      "Bonot",
      "Rawis",
      "Arimbay",
      "Bigaa",
      "Lidong",
      "San Isidro",
      "FIdel Surtida",
      "Santa Misericordia",
      "San Fernando",
      "Bonga Upper",
      "San Jose",
      "San Francisco",
      "San Isidro Ilawod",
      "San Lorenzo",
      "Tagas Tabacco",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.359, lon: 123.733 },
    isPrimary: false,
  },
  {
    name: "Legazpi to Manito",
    start: "Legazpi",
    end: "Manito",
    via: [],
    distance: 41,
    landmarks: [
      "SM City Legazpi",
      "Legazpi Grand Terminal",
      "Divine Word College of Legazpi",
      "Robinsons Supermarket Albay",
      "Jollibee Albay",
      "Legazpi City Hall",
      "St. Gregory the Great Cathedral",
      "Peñaranda Park",
      "Albay Provincial Capitol",
      "New Country Homes Subdivision",
      "Serenity Memorial Park",
      "Taysan Barangay Hall",
      "Santa Florentina Church",
      "Uma ni Islao Private Farm",
      "Homapon Barangay Hall",
      "Eco Park Agri-Tourism Farm",
      "Hacienda De Alamo",
      "Villa Conchita",
      "Banquerohan Barangay Hall",
      "Legazpi Cho Southen District Maternity Lying In Clinic",
      "Karagahan Falls",
      "Luksuhan Falls",
      "San Francisco Farm",
      "Buenavista Wharf and Boulevard",
      "Dalipay River Resort",
      "Cawayan Hut Bicol",
      "Zoie's White Beach Resort",
      "Aswang Bay",
      "Malobago View Deck",
      "Abion Falls",
      "Bulakbugak Spring Falls",
      "Tinapian Barangay Hall",
      "Manumbalay Barangay Hall",
      "Busay Falls",
      "Manito Municipal Hall",
    ],
    zones: [
      "Legazpi Port District",
      "Bitano",
      "Cabagnan",
      "Old Albay District",
      "Ilawod West",
      "Taysan",
      "Homapon",
      "Imaldnod",
      "Banquerohan",
      "San Francisco",
      "Cabacongan",
      "Malobago",
      "Tinapian",
      "Manumbalay",
      "Buyo",
      "Manito",
    ],
    startCoords: { lat: 13.147, lon: 123.751 },
    endCoords: { lat: 13.123, lon: 123.867 },
    isPrimary: false,
  },
];

// Function to fetch polyline from Google Maps Directions API
async function getPolyline(start, end, via) {
  try {
    const response = await gmaps.directions({
      params: {
        origin: start,
        destination: end,
        waypoints: via.length ? via : undefined,
        mode: "driving",
        region: "ph",
        key: GOOGLE_MAPS_API_KEY,
      },
    });

    if (response.data.routes.length > 0) {
      const polyline = response.data.routes[0].overview_polyline;
      console.log(`Fetched polyline for route from ${start} to ${end}`);
      return polyline;
    } else {
      console.warn(`No routes found from ${start} to ${end}`);
      return null;
    }
  } catch (error) {
    console.error(`Error fetching polyline from ${start} to ${end}:`, error);
    return null;
  }
}

// Function to upload routes to Firestore with polylines
async function uploadRoutes() {
  try {
    for (const route of routes) {
      // Fetch polyline
      const polyline = await getPolyline(route.start, route.end, route.via);

      // Add polyline to route object
      const routeWithPolyline = {
        ...route,
        path: polyline || "", // Use empty string if polyline fetch fails
      };

      // Upload to routes collection
      await setDoc(doc(db, "routes", route.name), routeWithPolyline);
      console.log(
        `Successfully uploaded route: ${route.name} with polyline: ${
          polyline ? "Yes" : "No"
        }`
      );
    }
    console.log("All routes uploaded successfully!");
  } catch (error) {
    console.error("Error uploading routes:", error);
  }
}

// Function to upload fares to Firestore
async function uploadFares() {
  try {
    for (const fare of fareMetrics) {
      await setDoc(doc(db, "fares", fare.distance.toString()), fare);
      console.log(
        `Successfully uploaded fare for distance: ${fare.distance}km`
      );
    }
    console.log("All fares uploaded successfully!");
  } catch (error) {
    console.error("Error uploading fares:", error);
  }
}

// Run both upload functions
async function uploadAllData() {
  await uploadRoutes();
  // await uploadFares();
}

uploadAllData();
